"""add_dc_type_and_return_tracking

Revision ID: 166ce5f9074b
Revises: e236dd883f21
Create Date: 2026-07-21 14:46:40.602713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '166ce5f9074b'
down_revision: Union[str, Sequence[str], None] = 'e236dd883f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
dc_type_enum = postgresql.ENUM(
    'WITH_BILL_INWARD',
    'WITH_BILL_OUTWARD',
    'WITHOUT_BILL_INWARD',
    'WITHOUT_BILL_OUTWARD',
    name='dctype'
)

def upgrade() -> None:
    # 1. Add COMPLETED to deliverystatus enum
    dc_type_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TYPE deliverystatus ADD VALUE IF NOT EXISTS 'COMPLETED'")
    
    # 2. Create dctype enum (Alembic handles this via sa.Enum)
    
    # 3. Add new columns with defaults
    op.add_column('delivery_challan_items', 
        sa.Column('quantity_sent', sa.Float(), nullable=False, server_default='0'))
    op.add_column('delivery_challan_items', 
        sa.Column('quantity_returned', sa.Float(), nullable=False, server_default='0'))
    
    # 4. Drop old columns
    op.drop_column('delivery_challan_items', 'quantity_delivered')
    op.drop_column('delivery_challan_items', 'quantity_requested')
    
    # 5. Add delivery_challans columns
    op.add_column('delivery_challans', 
        sa.Column('dc_type', 
            sa.Enum('WITH_BILL_INWARD', 'WITH_BILL_OUTWARD', 
                    'WITHOUT_BILL_INWARD', 'WITHOUT_BILL_OUTWARD', name='dctype'), 
            nullable=False, server_default='WITHOUT_BILL_OUTWARD'))
    op.add_column('delivery_challans', 
        sa.Column('expected_return_date', sa.Date(), nullable=True))
    op.add_column('delivery_challans', 
        sa.Column('is_returned', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('delivery_challans', 
        sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
    
    # 6. Fix delivery_date type
    op.alter_column('delivery_challans', 'delivery_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=True)
    
    # 7. Create indexes
    op.create_index(op.f('ix_delivery_challans_dc_type'), 'delivery_challans', ['dc_type'], unique=False)
    op.create_index(op.f('ix_delivery_challans_status'), 'delivery_challans', ['status'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_challans_status'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_dc_type'), table_name='delivery_challans')
    op.alter_column('delivery_challans', 'delivery_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('delivery_challans', 'returned_at')
    op.drop_column('delivery_challans', 'is_returned')
    op.drop_column('delivery_challans', 'expected_return_date')
    op.drop_column('delivery_challans', 'dc_type')
    op.add_column('delivery_challan_items', sa.Column('quantity_requested', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('delivery_challan_items', sa.Column('quantity_delivered', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('delivery_challan_items', 'quantity_returned')
    op.drop_column('delivery_challan_items', 'quantity_sent')
    # ### end Alembic commands ###
