"""add quotation tables

Revision ID: 2a01467616b8
Revises: 52022bdc1950
Create Date: 2026-06-15 15:16:24.286647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a01467616b8'
down_revision: Union[str, Sequence[str], None] = '52022bdc1950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_no', sa.String(length=50), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('client_email', sa.String(length=150), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', name='quotationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_id'), 'quotation', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_quotation_no'), 'quotation', ['quotation_no'], unique=False)
    
    op.create_table('quotation_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_line_item_id'), 'quotation_line_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_line_item_id'), table_name='quotation_line_item')
    op.drop_table('quotation_line_item')
    op.drop_index(op.f('ix_quotation_quotation_no'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_id'), table_name='quotation')
    op.drop_table('quotation')
    # ### end Alembic commands ###
