"""add delivery fields to stock ledger

Revision ID: 48cf3551eab3
Revises: f0b025257902
Create Date: 2026-06-26 10:48:03.794930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cf3551eab3'
down_revision: Union[str, Sequence[str], None] = 'f0b025257902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ledger', sa.Column('delivery_by', sa.String(length=100), nullable=True))
    op.add_column('stock_ledger', sa.Column('courier_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_ledger', 'courier_name')
    op.drop_column('stock_ledger', 'delivery_by')
    # ### end Alembic commands ###
