"""add_serial_delivery_challan_bridge

Revision ID: 4ffd49def0f5
Revises: 166ce5f9074b
Create Date: 2026-07-22 15:20:40.942577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ffd49def0f5'
down_revision: Union[str, Sequence[str], None] = '166ce5f9074b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_delivery_challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number_id', sa.Integer(), nullable=False),
    sa.Column('delivery_challan_id', sa.Integer(), nullable=False),
    sa.Column('delivery_challan_item_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_challan_item_id'], ['delivery_challan_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serial_number_id'], ['serial_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serial_delivery_challans_delivery_challan_id'), 'serial_delivery_challans', ['delivery_challan_id'], unique=False)
    op.create_index(op.f('ix_serial_delivery_challans_id'), 'serial_delivery_challans', ['id'], unique=False)
    op.create_index(op.f('ix_serial_delivery_challans_serial_number_id'), 'serial_delivery_challans', ['serial_number_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serial_delivery_challans_serial_number_id'), table_name='serial_delivery_challans')
    op.drop_index(op.f('ix_serial_delivery_challans_id'), table_name='serial_delivery_challans')
    op.drop_index(op.f('ix_serial_delivery_challans_delivery_challan_id'), table_name='serial_delivery_challans')
    op.drop_table('serial_delivery_challans')
    # ### end Alembic commands ###
