"""make_sku_nullable

Revision ID: 52022bdc1950
Revises: 87789f3f3abb
Create Date: 2026-06-12 11:49:58.159102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52022bdc1950'
down_revision: Union[str, Sequence[str], None] = '87789f3f3abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('model', 'date')
    op.drop_column('model', 'courier')
    op.drop_column('model', 'delivery_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('delivery_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model', sa.Column('courier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('model', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
