"""add hsn and delivery type

Revision ID: 85fe97398a63
Revises: c264f453bb94
Create Date: 2026-06-23 15:36:38.416150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fe97398a63'
down_revision: Union[str, Sequence[str], None] = 'c264f453bb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('quotation', sa.Column('delivery_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'delivery_type')
    op.drop_column('quotation', 'hsn_code')
    # ### end Alembic commands ###
