"""add_reference_no_to_delivery_challans

Revision ID: 86142d76481e
Revises: c0a1143d34c7
Create Date: 2026-07-20 11:20:19.119416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86142d76481e'
down_revision: Union[str, Sequence[str], None] = 'c0a1143d34c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challans', sa.Column('reference_no', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_delivery_challans_reference_no'), 'delivery_challans', ['reference_no'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_delivery_challans_reference_no'), table_name='delivery_challans')
    op.drop_column('delivery_challans', 'reference_no')
    # ### end Alembic commands ###
