"""expand_ledger_and_serial_number_tables

Revision ID: b2956786e2fc
Revises: 6a4b6f8aa053
Create Date: 2026-06-29 09:58:57.646322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2956786e2fc'
down_revision: Union[str, Sequence[str], None] = '6a4b6f8aa053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['stock_ledger.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serial_numbers_id'), 'serial_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_serial_numbers_serial_number'), 'serial_numbers', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serial_numbers_serial_number'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_id'), table_name='serial_numbers')
    op.drop_table('serial_numbers')
    # ### end Alembic commands ###
