"""add_discount_metrics

Revision ID: c264f453bb94
Revises: 2a01467616b8
Create Date: 2026-06-16 10:51:55.639805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c264f453bb94'
down_revision: Union[str, Sequence[str], None] = '2a01467616b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'quotation',
        sa.Column(
            'discount_rate',
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'quotation',
        sa.Column(
            'discount_amount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        )
    )

    op.alter_column('quotation', 'discount_rate', server_default=None)
    op.alter_column('quotation', 'discount_amount', server_default=None)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'discount_amount')
    op.drop_column('quotation', 'discount_rate')
    # ### end Alembic commands ###
