"""add-via-to-DC

Revision ID: ebf4d2ba322d
Revises: f1b01d542034
Create Date: 2026-08-22 16:34:13.572382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebf4d2ba322d'
down_revision: Union[str, Sequence[str], None] = 'f1b01d542034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challans', sa.Column('via', sa.String(length=100), nullable=True))
    op.add_column('delivery_challans', sa.Column('destination', sa.String(length=100), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('delivery_challans', 'destination')
    op.drop_column('delivery_challans', 'via')