"""add missing hsn and delivery columns

Revision ID: f0b025257902
Revises: e6ecf41f2782
Create Date: 2026-06-24 11:40:58.819228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b025257902'
down_revision: Union[str, Sequence[str], None] = 'e6ecf41f2782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'delivery_type')
    op.drop_column('quotation', 'hsn_code')
    op.add_column('quotation_line_item', sa.Column('hsn_code', sa.String(length=50), nullable=True))
    op.add_column('quotation_line_item', sa.Column('delivery_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_line_item', 'delivery_type')
    op.drop_column('quotation_line_item', 'hsn_code')
    op.add_column('quotation', sa.Column('hsn_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quotation', sa.Column('delivery_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
