"""add_client_to_purchase_and_supplier_to_sales

Revision ID: fb7ca5846edd
Revises: d501d2d7dfa9
Create Date: 2026-07-07 11:28:56.737710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7ca5846edd'
down_revision: Union[str, Sequence[str], None] = 'd501d2d7dfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_inward', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('purchase_inward', sa.Column('client_name', sa.String(length=200), nullable=True))
    op.alter_column('purchase_inward', 'expected_return_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Applicable only for DEMO_FROM_SUPPLIER. Overarching return deadline.',
               existing_nullable=True)
    op.create_index(op.f('ix_purchase_inward_client_id'), 'purchase_inward', ['client_id'], unique=False)
    op.create_foreign_key(None, 'purchase_inward', 'clients', ['client_id'], ['id'])
    op.alter_column('purchase_item', 'return_due_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Per-item return deadline for demo units',
               existing_nullable=True)
    op.alter_column('purchase_item', 'is_returned',
               existing_type=sa.BOOLEAN(),
               comment='True when all serial numbers of this line are returned',
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_item_serials_serial_number'), table_name='sales_item_serials')
    op.create_index(op.f('ix_sales_item_serials_serial_number'), 'sales_item_serials', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_item_serials_serial_number'), table_name='sales_item_serials')
    op.create_index(op.f('ix_sales_item_serials_serial_number'), 'sales_item_serials', ['serial_number'], unique=True)
    op.alter_column('purchase_item', 'is_returned',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when all serial numbers of this line are returned',
               existing_nullable=False)
    op.alter_column('purchase_item', 'return_due_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Per-item return deadline for demo units',
               existing_nullable=True)
    op.drop_constraint(None, 'purchase_inward', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_inward_client_id'), table_name='purchase_inward')
    op.alter_column('purchase_inward', 'expected_return_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Applicable only for DEMO_FROM_SUPPLIER. Overarching return deadline.',
               existing_nullable=True)
    op.drop_column('purchase_inward', 'client_name')
    op.drop_column('purchase_inward', 'client_id')
    # ### end Alembic commands ###
